[options]
addons_path = /mnt/extra-addons,/mnt/extra-addons/muk_web_theme-18.0.1.2.2
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$rNVayznHGKN0bi0FgPB.rw$xjdDBLQ0MiIo82UFWdESIsaR2HolSUNMNpRf0kXQsJvYnEQp9gly3glUVKK/Qq349qfQVKm97KWF2QdaPC.0YA
db_name = HDCARAMELO_PRODUCCION
dbfilter = ^HDCARAMELO_PRODUCCION$
list_db = True
proxy_mode = True
workers = 2
max_cron_threads = 1
limit_memory_soft = 1610612736
limit_memory_hard = 2147483648
limit_time_cpu = 60
limit_time_real = 120
limit_request = 8192
server_wide_modules = base,web
without_demo = all
